import * as constants from "./http-status-codes";

/**
 * Standard HTTP status codes
 */
export const HTTP_STATUS_CODE = {
	// 1xx
	CONTINUE: constants.CONTINUE,
	SWITCHING_PROTOCOLS: constants.SWITCHING_PROTOCOLS,
	PROCESSING: constants.PROCESSING,
	EARLY_HINTS: constants.EARLY_HINTS,

	// 2xx
	OK: constants.OK,
	CREATED: constants.CREATED,
	ACCEPTED: constants.ACCEPTED,
	NON_AUTHORITATIVE_INFORMATION: constants.NON_AUTHORITATIVE_INFORMATION,
	NO_CONTENT: constants.NO_CONTENT,
	RESET_CONTENT: constants.RESET_CONTENT,
	PARTIAL_CONTENT: constants.PARTIAL_CONTENT,
	MULTI_STATUS: constants.MULTI_STATUS,

	// 3xx
	MULTIPLE_CHOICES: constants.MULTIPLE_CHOICES,
	MOVED_PERMANENTLY: constants.MOVED_PERMANENTLY,
	MOVED_TEMPORARILY: constants.MOVED_TEMPORARILY,
	SEE_OTHER: constants.SEE_OTHER,
	USE_PROXY: constants.USE_PROXY,
	TEMPORARY_REDIRECT: constants.TEMPORARY_REDIRECT,
	PERMANENT_REDIRECT: constants.PERMANENT_REDIRECT,

	// 4xx
	BAD_REQUEST: constants.BAD_REQUEST,
	PAYMENT_REQUIRED: constants.PAYMENT_REQUIRED,
	FORBIDDEN: constants.FORBIDDEN,
	NOT_FOUND: constants.NOT_FOUND,
	METHOD_NOT_ALLOWED: constants.METHOD_NOT_ALLOWED,
	NOT_ACCEPTABLE: constants.NOT_ACCEPTABLE,
	REQUEST_TIMEOUT: constants.REQUEST_TIMEOUT,
	CONFLICT: constants.CONFLICT,
	GONE: constants.GONE,
	LENGTH_REQUIRED: constants.LENGTH_REQUIRED,
	REQUEST_TOO_LONG: constants.REQUEST_TOO_LONG,
	REQUEST_URI_TOO_LONG: constants.REQUEST_URI_TOO_LONG,
	REQUESTED_RANGE_NOT_SATISFIABLE: constants.REQUESTED_RANGE_NOT_SATISFIABLE,
	UNSUPPORTED_MEDIA_TYPE: constants.UNSUPPORTED_MEDIA_TYPE,
	EXPECTATION_FAILED: constants.EXPECTATION_FAILED,
	UPGRADE_REQUIRED: constants.UPGRADE_REQUIRED,
	MISDIRECTED_REQUEST: constants.MISDIRECTED_REQUEST,
	UNPROCESSABLE_ENTITY: constants.UNPROCESSABLE_ENTITY,
	LOCKED: constants.LOCKED,
	FAILED_DEPENDENCY: constants.FAILED_DEPENDENCY,
	PRECONDITION_REQUIRED: constants.PRECONDITION_REQUIRED,
	TOO_MANY_REQUESTS: constants.TOO_MANY_REQUESTS,
	REQUEST_HEADER_FIELDS_TOO_LARGE: constants.REQUEST_HEADER_FIELDS_TOO_LARGE,
	UNAUTHORIZED: constants.UNAUTHORIZED,
	PROXY_AUTHENTICATION_REQUIRED: constants.PROXY_AUTHENTICATION_REQUIRED,

	// 5xx
	INTERNAL_SERVER_ERROR: constants.INTERNAL_SERVER_ERROR,
	NOT_IMPLEMENTED: constants.NOT_IMPLEMENTED,
	BAD_GATEWAY: constants.BAD_GATEWAY,
	SERVICE_UNAVAILABLE: constants.SERVICE_UNAVAILABLE,
	GATEWAY_TIMEOUT: constants.GATEWAY_TIMEOUT,
	HTTP_VERSION_NOT_SUPPORTED: constants.HTTP_VERSION_NOT_SUPPORTED,
	INSUFFICIENT_STORAGE: constants.INSUFFICIENT_STORAGE,
	IM_A_TEAPOT: constants.IM_A_TEAPOT,
	INSUFFICIENT_SPACE_ON_RESOURCE: constants.INSUFFICIENT_SPACE_ON_RESOURCE,
	METHOD_FAILURE: constants.METHOD_FAILURE,
	NETWORK_AUTHENTICATION_REQUIRED: constants.NETWORK_AUTHENTICATION_REQUIRED,
	UNAVAILABLE_FOR_LEGAL_REASONS: constants.UNAVAILABLE_FOR_LEGAL_REASONS,
} as const;


